version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: firewall_prod
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file: ./backend/.env.prod
    depends_on: ['db']
    ports: ["4000:4000"]
    volumes:
      - ./backend/logs:/app/logs
    restart: always

  frontend:
    build:
      context: ./frontend
    env_file: ./frontend/.env.prod
    depends_on: [backend]
    ports: ["80:3000"]
    restart: always

volumes:
  db-data:
